apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cluster.giantswarm.io
spec:
  caBundle: '{{ .Values.CA }}'
  group: cluster.giantswarm.io
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: health-service
    namespace: giantswarm
