apiVersion: v1
kind: ConfigMap
metadata:
  name: health-service-configmap
  namespace: giantswarm
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      provider:
        kind: '{{ .Values.Installation.V1.Provider.Kind }}'
