apiVersion: v1
kind: Service
metadata:
  name: health-service
  namespace: giantswarm
  labels:
    app: health-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8000
  selector:
    app: health-service
