name: Nancy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Running Nancy dependency scanner
    - name: Nancy for GitHub Actions
      uses: sonatype-nexus-community/nancy-github-action@1.0.0

